package errors

const (
	BAD_ACCEPT_HEADER_ERR       = "BAD_ACCEPT_HEADER_ERR"
	BAD_CONTENT_TYPE_HEADER_ERR = "BAD_CONTENT_TYPE_HEADER_ERR"
	BAD_ACCEPT_LANG_HEADER_ERR  = "BAD_ACCEPT_LANG_HEADER_ERR"
	BAD_HTTP_METHOD_VERB_ERR    = "BAD_HTTP_METHOD_VERB_ERR"
	UNEXPECTED_ERR              = "UNEXPECTED_ERR"
)
